server:
  port: 8321

gogidix:
  logging:
    retention: ${GOGIDIX_LOGGING_RETENTION:30d}
    mongo-enabled: ${GOGIDIX_LOGGING_MONGO_ENABLED:false}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI:}

management:
  endpoints:
    web:
      exposure:
        include: health,info
