server:
  port: 8320

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  data:
    mongodb:
      uri: ${MONGODB_URI:}
      database: ${MONGODB_DATABASE:integration_adapters_service}
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      username: ${REDIS_USERNAME:}
      database: 25
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms
  datasource:
    url: jdbc:h2:mem:integrationdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

management:
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    redis:
      enabled: false
    kafka:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus