export default function App() {
  return (
    <div style={{ fontFamily: 'system-ui', padding: 24 }}>
      <h1>Ui Component Library</h1>
      <p>React Web (JavaScript) template generated by Gogidix-Saas-Code-gen.</p>
    </div>
  );
}
