package com.gogidix.rapidassist.ai.chatbot.domain.model;

/**
 * Enumeration representing the type of message in a chatbot conversation.
 */
public enum MessageType {

    /**
     * Message sent by the user
     */
    USER,

    /**
     * Response generated by the chatbot
     */
    BOT,

    /**
     * System notification or informational message
     */
    SYSTEM,

    /**
     * Error message
     */
    ERROR
}
