<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.gogidix.rapidassist</groupId>
        <artifactId>foundation-domain</artifactId>
        <version>1.0.0</version>
        <relativePath>../../../pom.xml</relativePath>
    </parent>

    <artifactId>central-configuration</artifactId>
    <packaging>pom</packaging>
    <name>Gogidix Central Configuration Services</name>

    <modules>
        <module>config-service</module>
        <module>dynamic-routing-config-service</module>
        <module>feature-flags-service</module>
        <module>rate-limit-policy-service</module>
        <module>release-rollout-config-service</module>
        <module>tenancy-configuration-service</module>
    </modules>
</project>
