sonar.organization=Gogidix-Road-assist
sonar.projectKey=Gogidix-Road-assist_foundation-domain
sonar.projectName=Foundation Domain
sonar.sources=shared-libraries/Backend/Java
sonar.tests=shared-libraries/Backend/Java/**/src/test
sonar.java.binaries=target/classes
sonar.jacoco.reportPaths=target/jacoco.exec
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
sonar.coverage.minimum=70
sonar.duplications.minimum=3
