sonar.organization=ggx-insurance-saas
sonar.projectKey=ggx-insurance-saas_foundation-domain
sonar.projectName=Foundation Domain
sonar.projectVersion=1.0

sonar.sources=central-configuration,shared-infrastructure,orchestration-services,ai-services,shared-libraries
sonar.tests=**/src/test
sonar.test.inclusions=**/*Test.java,**/*IT.java

sonar.java.binaries=**/target/classes
sonar.java.test.binaries=**/target/test-classes

sonar.jacoco.reportPaths=**/target/jacoco.exec
sonar.coverage.jacoco.xmlReportPaths=**/target/site/jacoco/jacoco.xml

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300

sonar.coverage.exclusions=**/config/**,**/dto/**,**/entity/**,**/model/**,**/Application.java
sonar.test.exclusions=**/target/**

sonar.scm.revision=${{ github.sha }}
sonar.buildbreaker.queryMaxAttempts=30
sonar.buildbreaker.queryInterval=5000
