apiVersion: v2
name: foundation-domain
description: Gogidix Road Assist SaaS — Foundation Domain (39 microservices)
type: application
version: 1.0.0
appVersion: "1.0.0"
maintainers:
  - name: gogidix-platform
    email: platform@gogidix.com
home: https://github.com/Gogidix-Road-assist/foundation-domain
sources:
  - https://github.com/Gogidix-Road-assist/foundation-domain
keywords:
  - gogidix
  - road-assist
  - foundation-domain
  - microservices
  - saas
