server:
  port: 8328
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  data:
    mongodb:
      uri: ${MONGODB_URI:}
      database: ${MONGODB_DATABASE:service_health_monitor}
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      username: ${REDIS_USERNAME:}
      database: 31
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms
  application:
    name: service-health-monitor

management:
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    redis:
      enabled: false
    kafka:
      enabled: false