package com.gogidix.rapidassist.orchestration.reporting.domain.port.in;

import com.gogidix.rapidassist.orchestration.reporting.domain.model.Report;

import java.util.List;
import java.util.Optional;

/**
 * Input port for Report generation operations.
 * Defines the contract for report generation use cases.
 */
public interface ReportGenerationPort {

    /**
     * Generate a new report
     */
    Report generateReport(String reportType, String outputFormat, String templateId,
                         java.util.Map<String, Object> parameters, String generatedBy, String tenantId);

    /**
     * Generate report from schedule
     */
    Report generateScheduledReport(String scheduleId, String tenantId);

    /**
     * Get report by ID
     */
    Optional<Report> getReport(String reportId);

    /**
     * Get reports by tenant
     */
    List<Report> getReportsByTenant(String tenantId);

    /**
     * Get reports by type
     */
    List<Report> getReportsByType(String tenantId, String reportType);

    /**
     * Get reports by status
     */
    List<Report> getReportsByStatus(String tenantId, String status);

    /**
     * Get reports generated by user
     */
    List<Report> getReportsByUser(String tenantId, String userId);

    /**
     * Get report file path for download
     */
    Optional<String> getReportFilePath(String reportId);

    /**
     * Delete report
     */
    void deleteReport(String reportId);

    /**
     * Get report statistics
     */
    ReportStatistics getReportStatistics(String tenantId);

    /**
     * Record download event
     */
    void recordDownload(String reportId, String userId);

    /**
     * Mark report as expired
     */
    void markAsExpired(String reportId);

    /**
     * Clean up expired reports
     */
    int cleanupExpiredReports();

    record ReportStatistics(
        long totalReports,
        long completedReports,
        long failedReports,
        long pendingReports,
        long totalFileSize
    ) {}
}
