apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "foundation-domain.fullname" . }}-netpol
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "foundation-domain.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      domain: foundation
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.global.namespace }}
    - podSelector: {}
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
  egress:
  - {}
