apiVersion: v1
kind: Secret
metadata:
  name: {{ include "foundation-domain.fullname" . }}-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "foundation-domain.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGODB_URI: "{{ .Values.secrets.mongodbUri }}"
  REDIS_HOST: "{{ .Values.secrets.redisHost }}"
  REDIS_PORT: "{{ .Values.secrets.redisPort }}"
  REDIS_PASSWORD: "{{ .Values.secrets.redisPassword }}"
  REDIS_USERNAME: "{{ .Values.secrets.redisUsername }}"
  SPRING_DATA_REDIS_PASSWORD: "{{ .Values.secrets.redisPassword }}"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.secrets.kafkaBootstrapServers | default "" }}"
