package com.gogidix.rapidassist.reporting.read.model.service.infrastructure.repository;

import com.gogidix.rapidassist.reporting.read.model.service.domain.model.Report;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.Instant;
import java.util.List;
import java.util.Optional;

/**
 * Repository for Report entity with CRITICAL tenant isolation.
 * <p>
 * CATASTROPHIC SECURITY WARNING: Reports are READ-ONLY aggregated views.
 * Without proper tenant filtering, Tenant A could access ALL of Tenant B's data.
 * <p>
 * ALL query methods MUST filter by tenantId to prevent cross-tenant data leakage.
 * Direct access to findAll() or methods without tenant filtering is BLOCKED.
 *
 * @author Gogidix
 * @since 1.0.0
 */
@Repository
public interface ReportRepository extends JpaRepository<Report, String> {

    /**
     * Find all reports for a specific tenant.
     * CRITICAL: This is the ONLY way to list reports - tenant filtering is MANDATORY.
     *
     * @param tenantId The tenant ID
     * @return List of reports for the tenant
     */
    @Query("SELECT r FROM Report r WHERE r.tenantId = :tenantId ORDER BY r.createdAt DESC")
    List<Report> findByTenantId(@Param("tenantId") String tenantId);

    /**
     * Find report by ID and tenant ID.
     * Both ID and tenantId must match for security.
     *
     * @param id       The report ID
     * @param tenantId The tenant ID
     * @return Optional report if found and belongs to tenant
     */
    @Query("SELECT r FROM Report r WHERE r.id = :id AND r.tenantId = :tenantId")
    Optional<Report> findByIdAndTenantId(@Param("id") String id, @Param("tenantId") String tenantId);

    /**
     * Find reports by tenant ID and report type.
     *
     * @param tenantId   The tenant ID
     * @param reportType The report type
     * @return List of reports of the given type
     */
    @Query("SELECT r FROM Report r WHERE r.tenantId = :tenantId AND r.reportType = :reportType ORDER BY r.createdAt DESC")
    List<Report> findByTenantIdAndReportType(@Param("tenantId") String tenantId, @Param("reportType") String reportType);

    /**
     * Find reports by tenant ID and status.
     *
     * @param tenantId The tenant ID
     * @param status   The report status
     * @return List of reports with the given status
     */
    @Query("SELECT r FROM Report r WHERE r.tenantId = :tenantId AND r.status = :status ORDER BY r.createdAt DESC")
    List<Report> findByTenantIdAndStatus(@Param("tenantId") String tenantId, @Param("status") Report.ReportStatus status);

    /**
     * Find reports by tenant ID, report type, and status.
     * Composite query for efficient filtering.
     *
     * @param tenantId   The tenant ID
     * @param reportType The report type
     * @param status     The report status
     * @return List of reports matching all criteria
     */
    @Query("SELECT r FROM Report r WHERE r.tenantId = :tenantId AND r.reportType = :reportType AND r.status = :status ORDER BY r.createdAt DESC")
    List<Report> findByTenantIdAndReportTypeAndStatus(
            @Param("tenantId") String tenantId,
            @Param("reportType") String reportType,
            @Param("status") Report.ReportStatus status
    );

    /**
     * Find reports by tenant ID within a date range.
     *
     * @param tenantId  The tenant ID
     * @param startDate Start of date range
     * @param endDate   End of date range
     * @return List of reports in the date range
     */
    @Query("SELECT r FROM Report r WHERE r.tenantId = :tenantId AND r.createdAt BETWEEN :startDate AND :endDate ORDER BY r.createdAt DESC")
    List<Report> findByTenantIdAndCreatedAtBetween(
            @Param("tenantId") String tenantId,
            @Param("startDate") Instant startDate,
            @Param("endDate") Instant endDate
    );

    /**
     * Find reports by tenant ID and generated by user.
     *
     * @param tenantId    The tenant ID
     * @param generatedBy The user who generated the report
     * @return List of reports generated by the user
     */
    @Query("SELECT r FROM Report r WHERE r.tenantId = :tenantId AND r.generatedBy = :generatedBy ORDER BY r.createdAt DESC")
    List<Report> findByTenantIdAndGeneratedBy(@Param("tenantId") String tenantId, @Param("generatedBy") String generatedBy);

    /**
     * Find active (non-expired) reports by tenant ID.
     *
     * @param tenantId The tenant ID
     * @return List of active reports
     */
    @Query("SELECT r FROM Report r WHERE r.tenantId = :tenantId AND (r.expiresAt IS NULL OR r.expiresAt > :now) ORDER BY r.createdAt DESC")
    List<Report> findActiveByTenantId(@Param("tenantId") String tenantId, @Param("now") Instant now);

    /**
     * Find expired reports by tenant ID.
     *
     * @param tenantId The tenant ID
     * @return List of expired reports
     */
    @Query("SELECT r FROM Report r WHERE r.tenantId = :tenantId AND r.expiresAt IS NOT NULL AND r.expiresAt <= :now")
    List<Report> findExpiredByTenantId(@Param("tenantId") String tenantId, @Param("now") Instant now);

    /**
     * Find reports by tenant ID that are completed and not expired.
     *
     * @param tenantId The tenant ID
     * @return List of ready reports
     */
    @Query("SELECT r FROM Report r WHERE r.tenantId = :tenantId AND r.status = 'COMPLETED' AND (r.expiresAt IS NULL OR r.expiresAt > :now) ORDER BY r.createdAt DESC")
    List<Report> findReadyByTenantId(@Param("tenantId") String tenantId, @Param("now") Instant now);

    /**
     * Find reports by tenant ID with file path (exported reports).
     *
     * @param tenantId The tenant ID
     * @return List of exported reports
     */
    @Query("SELECT r FROM Report r WHERE r.tenantId = :tenantId AND r.filePath IS NOT NULL ORDER BY r.createdAt DESC")
    List<Report> findExportedByTenantId(@Param("tenantId") String tenantId);

    /**
     * Count reports by tenant ID and status.
     *
     * @param tenantId The tenant ID
     * @param status   The report status
     * @return Count of reports
     */
    @Query("SELECT COUNT(r) FROM Report r WHERE r.tenantId = :tenantId AND r.status = :status")
    long countByTenantIdAndStatus(@Param("tenantId") String tenantId, @Param("status") Report.ReportStatus status);

    /**
     * Count reports by tenant ID and report type.
     *
     * @param tenantId   The tenant ID
     * @param reportType The report type
     * @return Count of reports
     */
    @Query("SELECT COUNT(r) FROM Report r WHERE r.tenantId = :tenantId AND r.reportType = :reportType")
    long countByTenantIdAndReportType(@Param("tenantId") String tenantId, @Param("reportType") String reportType);

    /**
     * Delete expired reports for a tenant.
     *
     * @param tenantId The tenant ID
     * @param now      Current time
     */
    @Query("DELETE FROM Report r WHERE r.tenantId = :tenantId AND r.expiresAt IS NOT NULL AND r.expiresAt <= :now")
    void deleteExpiredByTenantId(@Param("tenantId") String tenantId, @Param("now") Instant now);

    /**
     * Check if a report exists by ID and tenant ID.
     *
     * @param id       The report ID
     * @param tenantId The tenant ID
     * @return true if exists
     */
    @Query("SELECT CASE WHEN COUNT(r) > 0 THEN true ELSE false END FROM Report r WHERE r.id = :id AND r.tenantId = :tenantId")
    boolean existsByIdAndTenantId(@Param("id") String id, @Param("tenantId") String tenantId);

    /**
     * CRITICAL: BLOCK direct findAll() to prevent CATASTROPHIC cross-tenant data access.
     * Reports aggregate data from all tenants - direct access would leak EVERYTHING.
     */
    @Override
    default List<Report> findAll() {
        throw new UnsupportedOperationException(
                "CRITICAL: Direct access to all reports is BLOCKED to prevent CATASTROPHIC data leakage. " +
                        "Use findByTenantId() to access reports for a specific tenant."
        );
    }

    /**
     * CRITICAL: BLOCK findAllById() to prevent cross-tenant data access.
     */
    @Override
    default List<Report> findAllById(Iterable<String> ids) {
        throw new UnsupportedOperationException(
                "CRITICAL: Batch access to reports is BLOCKED for security. " +
                        "Use findByIdAndTenantId() for each report individually."
        );
    }

    /**
     * CRITICAL: BLOCK deleteAll() to prevent mass deletion.
     */
    @Override
    default void deleteAll() {
        throw new UnsupportedOperationException(
                "CRITICAL: Mass deletion is BLOCKED for security. " +
                        "Delete reports by tenant ID only."
        );
    }

    /**
     * CRITICAL: BLOCK deleteAllById() to prevent mass deletion.
     */
    @Override
    default void deleteAllById(Iterable<? extends String> ids) {
        throw new UnsupportedOperationException(
                "CRITICAL: Batch deletion is BLOCKED for security. " +
                        "Use deleteByIdAndTenantId() for each report individually."
        );
    }

    /**
     * Delete a report by ID and tenant ID.
     *
     * @param id       The report ID
     * @param tenantId The tenant ID
     */
    @Query("DELETE FROM Report r WHERE r.id = :id AND r.tenantId = :tenantId")
    void deleteByIdAndTenantId(@Param("id") String id, @Param("tenantId") String tenantId);

    /**
     * Delete all reports for a specific tenant.
     * WARNING: This is a destructive operation.
     *
     * @param tenantId The tenant ID
     */
    @Query("DELETE FROM Report r WHERE r.tenantId = :tenantId")
    void deleteAllByTenantId(@Param("tenantId") String tenantId);
}
