<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.gogidix.rapidassist</groupId>
        <artifactId>foundation-domain</artifactId>
        <version>1.0.0</version>
        <relativePath>../../../pom.xml</relativePath>
    </parent>

    <artifactId>shared-libraries</artifactId>
    <packaging>pom</packaging>
    <name>Gogidix Shared Libraries</name>

    <modules>
        <module>shared-request-context-library</module>
        <module>shared-audit-library</module>
        <module>shared-cors-config</module>
        <module>shared-dto-library</module>
        <module>shared-exception-library</module>
        <module>shared-idempotency-library</module>
        <module>shared-mapper-library</module>
        <module>shared-observability-library</module>
        <module>shared-persistence-library</module>
        <module>shared-security-library</module>
        <module>shared-validation-library</module>
    </modules>
</project>
