package com.gogidix.rapidassist.orchestration.reporting.application.dto;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Map;

/**
 * Request DTO for creating a new report
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CreateReportRequest {

    @NotBlank(message = "Report name is required")
    private String name;

    private String description;

    @NotNull(message = "Report type is required")
    private ReportDTO.ReportTypeDTO reportType;

    @NotNull(message = "Output format is required")
    private ReportDTO.OutputFormatDTO outputFormat;

    @NotBlank(message = "Template ID is required")
    private String templateId;

    private Map<String, Object> parameters;

    private Integer retentionDays;

    private Boolean isScheduled;

    private String scheduleId;

    @NotBlank(message = "Generated by is required")
    private String generatedBy;

    @NotBlank(message = "Tenant ID is required")
    private String tenantId;

    private Map<String, Object> metadata;
}
