server:
  port: 8318

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
  data:
    mongodb:
      uri: ${MONGODB_URI:}
      database: ${MONGODB_DATABASE:identity_access_service}
      auto-index-creation: true
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      username: ${REDIS_USERNAME:}
      database: 23
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms
      database: ${GOGIDIX_IDENTITY_ACCESS_DB:identity_access}

management:
  metrics:
    export:
      prometheus:
        enabled: true
  health:
    redis:
      enabled: false
    kafka:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus