server:
  port: 8090

spring:
  application:
    name: database-indexing-service
  data:
    mongodb:
      uri: ${MONGODB_URI:}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
